expname: spect_emission
data:
  type: spect
  manifest: data/manifest_abs.csv
  imsize: null
  white_bkgd: false
  fixed_poses: ap_pa
  orthographic: true
  near: 0.0
  far: 1.0
  ray_split_ratio: 0.8
  act_scale: 1.0
  proj_input_source: normalized
  split_by_patient_id: true
  split_seed: 0
  split_mode: counts
  split_train_count: 16
  split_val_count: 1
  split_test_count: 3
  radius: 0.5
  fov: 60.0
  voxel_mm: 1.5
  use_anisotropic_radius: true
  radius_xyz_cm:
  - 48.825
  - 19.2
  - 19.2
  auto_near_far_from_radius: true
  augmentation: false
  umin: 0.0
  umax: 0.0
  vmin: 0.0
  vmax: 0.0
nerf:
  i_embed: 0
  multires: 10
  multires_views: 0
  use_viewdirs: false
  use_attenuation: true
  attenuation_debug: false
  atten_scale: 1.0
  N_samples: 96
  N_importance: 0
  netdepth: 8
  netwidth: 256
  netdepth_fine: 8
  netwidth_fine: 256
  perturb: 1
  raw_noise_std: 0.0
  decrease_noise: false
z_dist:
  type: gauss
  dim: 256
  dim_appearance: 128
ray_sampler:
  min_scale: 1.0
  max_scale: 1.0
  scale_anneal: -1.0
  N_samples: 0
discriminator:
  ndf: 64
  hflip: false
training:
  outdir: ./results_spect
  model_file: model_spect.pt
  monitoring: tensorboard
  use_amp: false
  nworkers: 4
  batch_size: 1
  chunk: 8192
  netchunk: 16384
  tv_weight: 0.001
  tv_weight_mu: 0.0
  tv_mu_sigma: 1.0
  mu_gate_weight: 0.0
  mu_gate_mode: none
  mu_gate_center: 0.2
  mu_gate_width: 0.1
  tv3d_weight: 0.0
  tv3d_grid_size: 32
  act_loss_weight: 0.1
  act_samples: 16384
  act_pos_weight: 2.0
  act_pos_fraction: 0.5
  act_pos_threshold: 1.0e-08
  ct_loss_weight: 0.0
  ct_threshold: 0.05
  optimizer: adam
  lr_g: 0.00025
  lr_d: 0.0
  lr_anneal: 1.0
  lr_anneal_every: []
  val_interval: 200
  debug_eval_flow: false
  run_final_test: true
  equalize_lr: false
  gan_type: none
  reg_type: none
  reg_param: 0.0
  aug_policy: none
  n_test_samples_with_same_shape_code: 1
  take_model_average: false
  model_average_beta: 0.999
  model_average_reinit: false
  restart_every: -1
  save_best: recon_loss
  fid_every: 0
  print_every: 10
  sample_every: 0
  save_every: 500
  backup_every: 0
  video_every: 0
